export const API_ENDPOINTS = {
    AUTH: {
        LOGIN: '/api/v1/auth/login',
        REGISTER: '/api/v1/auth/register',
        GOOGLE: '/api/v1/auth/google',
        LOGOUT: '/api/v1/auth/logout',
        PROFILE: '/api/v1/auth/profile',
        FORGOT_PASSWORD: '/api/v1/auth/forgot-password',
        RESET_PASSWORD: '/api/v1/auth/reset-password',
        REFRESH: '/api/v1/auth/refresh',
        VERIFY_EMAIL: '/api/v1/auth/verify-email',
        RESEND_VERIFICATION: '/api/v1/auth/resend-verification',
    },
    USERS: {
        LIST: '/users',
        CREATE: '/users',
        DETAIL: (id: string) => `/users/${id}`,
        UPDATE: (id: string) => `/users/${id}`,
        PATCH: (id: string) => `/users/${id}`,
        DELETE: (id: string) => `/users/${id}`,
        SOFT_DELETE: (id: string) => `/users/${id}/soft-delete`,
    },
    AUDIT_LOGS: '/api/v1/audit-logs',
    USER_DEVICES: (id: string) => `/users/${id}/devices`,
} as const;
